import {useState} from 'react';
import type {TrackingData} from '../lib/types';
import {formatNumber} from '../lib/format';
export function Research({tracking}:{tracking:TrackingData}){
 const [strategy,setStrategy]=useState('soxl_csp'),[ticker,setTicker]=useState('All');
 const rows=tracking.signals.filter(r=>r.strategy===strategy&&(ticker==='All'||r.ticker===ticker)).sort((a,b)=>b.signalAt.localeCompare(a.signalAt));
 const unique=new Set(rows.map(r=>r.contractId)).size;
 const hits=rows.filter(r=>r.outcome.hit80Within5D===true);
 const matured=rows.filter(r=>r.outcome.hit80Within5D===true||r.outcome.expired===true||(tracking.generatedAt&&Date.parse(tracking.generatedAt)-Date.parse(r.signalAt)>=5*86400000));
 return <section className="wideWorkspace"><div className="sectionHead"><div><h2>策略驗證 · Signal research</h2><p>前推報價觀察。只記錄可觀察到的達標，不推定成交、指派或未觀察到的平倉。</p></div></div><div className="filterBar"><label>策略版本<select value={strategy} onChange={e=>{setStrategy(e.target.value);setTicker('All')}}><option value="soxl_csp">SOXL 風險優先 · 2026-09-07.v1</option><option value="weekly_csp">舊 Weekly CSP · Legacy</option><option value="leaps">舊 LEAPS · Legacy</option></select></label><label>標的<select value={ticker} onChange={e=>setTicker(e.target.value)}><option value="All">全部</option>{[...new Set(tracking.signals.filter(r=>r.strategy===strategy).map(r=>r.ticker))].sort().map(t=><option key={t}>{t}</option>)}</select></label></div><div className="metricGrid"><div className="metric"><span>訊號／不同合約</span><strong>{rows.length} / {unique}</strong><small>不等於獨立交易樣本</small></div><div className="metric"><span>五日觀察已成熟</span><strong>{matured.length}</strong><small>其餘不放入五日比例分母</small></div><div className="metric"><span>五日內 80% capture</span><strong>{strategy==='leaps'||!matured.length?'—':`${formatNumber(hits.length/matured.length*100,1)}%`}</strong><small>達標頻率，非獲利勝率</small></div><div className="metric"><span>開倉估價口徑</span><strong>{strategy==='soxl_csp'?'Bid → Ask':'Legacy Mid'}</strong><small>SOXL v1：同日同合約只留首次訊號</small></div></div>{!rows.length?<div className="emptyState"><h3>新規則尚未累積訊號</h3><p>排程已支援 SOXL v1；下一次有效行情收集才開始前推觀察，不回填舊策略為新策略績效。</p></div>:<><p className="notice">{strategy==='soxl_csp'?'未扣手續費；記錄 50%／70%／80% 首次達標與最差觀察值。':'舊版使用重複掃描訊號與 Mid 假設開倉，保留原始紀錄供比較。'} 缺漏報價可能漏掉達標；過期無 80% 紀錄不代表虧損。</p><div className="tableWrap"><table><thead><tr><th>訊號</th><th>合約</th><th>50%／70%／80%</th><th>最佳／最差 capture</th><th>觀察／狀態</th></tr></thead><tbody>{rows.slice(0,100).map(r=><tr key={r.id}><td>{r.signalAt.slice(0,10)}<small>{r.strategyVersion??'legacy'}</small></td><td>{r.ticker} {r.expiration}<small>{r.strike} {r.optionType}</small></td><td>{[50,70,80].map(n=><small key={n}>{n}%：{String(r.outcome[`hit${n}At`]??'未觀察到').slice(0,10)}</small>)}</td><td>{typeof r.outcome.bestProfitCapturePct==='number'?`${r.outcome.bestProfitCapturePct}%`:'—'}<small>{typeof r.outcome.worstProfitCapturePct==='number'?`${formatNumber(r.outcome.worstProfitCapturePct,1)}%`:'—'}</small></td><td>{r.observations.count} 次<small>{String(r.outcome.status??'—')}</small></td></tr>)}</tbody></table></div><p className="sourceLine">顯示最近 {Math.min(100,rows.length)}／{rows.length} 個訊號。</p></>}</section>;
}
